### ISSUE TITLE
Crop rectangle does not fit within image data

### ISSUE THREAD

**Issue by lgabardos** [mitoyarzun/zxingfragmentlib#15]
Hi,
I updated the library yesterday and, i got this issue...
## 

java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
    at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50)
    at com.welcu.android.zxingfragmentlib.camera.CameraManager.buildLuminanceSource(CameraManager.java:360)
    at com.welcu.android.zxingfragmentlib.DecodeHandler.decode(DecodeHandler.java:77)
    at com.welcu.android.zxingfragmentlib.DecodeHandler.handleMessage(DecodeHandler.java:56)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
        at com.welcu.android.zxingfragmentlib.DecodeThread.run(DecodeThread.java:101)
## 

It appears when I use the phone in landscape and open the my BarcodeScannerFragment.

I googled this error and, obviously, it means the device's camera driver has a bug. 

BUT, i got the issue on multiple devices... and I don't really how to fix it...

Any clue ? Thanks

Laurent

**Comment by nijian81** [comment]
up stair id correct , perfect .i resolve my trubel

**Comment by gzp1124** [comment]
in PlanarYUVLuminanceSource  49 line
`if (left + width > dataWidth || top + height > dataHeight) {
      throw new IllegalArgumentException("Crop rectangle does not fit within image data.");
    }`
i change rect calculate
`int cameraWidth = cameraManager.getCameraResolution().y;
            int cameraHeight = cameraManager.getCameraResolution().x;`
to
`int cameraWidth = isVertical?cameraManager.getCameraResolution().y:cameraManager.getCameraResolution().x;
        int cameraHeight = isVertical?cameraManager.getCameraResolution().x:cameraManager.getCameraResolution().y;`
it worked.  :)

**Comment by dafeige8** [comment]
Upstairs, your "int cameraWidth = cameraManager.getCameraResolution().y; int cameraHeight = cameraManager.getCameraResolution().x;" in which file, is customized or Zxing comes with？

**Comment by soenkegissel** [comment]
I had similar issue. Using zxing-android-embedded (https://github.com/journeyapps/zxing-android-embedded).

Zxing greater version 3.3.0 bring this issue to some users of my app.

Downgrading to 3.3.0 fix it.

dependencies {
implementation('com.journeyapps:zxing-android-embedded:3.6.0') 
{ transitive = false }
implementation 'com.google.zxing:core:3.3.0'
}
This version is even compatible down to API level 14.
